### ISSUE TITLE
Problems with python3-z3 on Debian

### ISSUE THREAD

**Issue by dgpv** [dgpv/bsst#34]
> Maybe I did not understand, but if you analyze with `--z3-enabled=true`, the report will show that the enforcement condition is 'always true'

z3 isn't working for me; I'm getting:

```
Exception ignored in: <function AstRef.__del__ at 0x7f076dd445e0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/z3/z3.py", line 351, in __del__
  File "/usr/lib/python3/dist-packages/z3/z3.py", line 724, in as_ast
TypeError: 'NoneType' object is not callable
Exception ignored in: <function AstRef.__del__ at 0x7f076dd445e0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/z3/z3.py", line 351, in __del__
  File "/usr/lib/python3/dist-packages/z3/z3.py", line 724, in as_ast
TypeError: 'NoneType' object is not callable
```

python3-z3 4.8.12-3.1+b2 from Debian, commit 942f7bca3a360e22cf07b54818e0dfae80f33aae from bsst.

_Originally posted by @ajtowns in https://github.com/dgpv/bsst/issues/33#issuecomment-2123162453_

**Comment by ajtowns** [comment]
Yeah, looks like the debian package hasn't been updated since 2022, so probably not your problem :(
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014978

**Comment by dgpv** [comment]
OK

I will leave the issue open in case anyone have the same problem, so they can have a reference to the debian bug
